---
template:
  id: test-template
  author: test-user
  type: project
  display: Test Template
  version: 0.1.0
  url: https://github.com/petergmurphy/template-peter

puppet_class:
  module_name: module_name
